name: Deploy Swagger to Apifox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate Swagger JSON
        run: npm run generate-swagger

      - name: List files
        run: ls -la

      - name: Upload Swagger to Apifox
        run: bash ./github/workflows/upload_to_apifox.sh
        env:
          APIFOX_PROJECT_ID: ${{ secrets.APIFOX_PROJECT_ID }}
          APIFOX_API_TOKEN: ${{ secrets.APIFOX_API_TOKEN }}